name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install packages
              run: |
                  yarn install

            - name: Build @blocz/detect-imports
              run: |
                  yarn build
              working-directory: ./packages/detect-imports

            - name: Build @blocz/mdx-live
              run: |
                  yarn build
              working-directory: ./packages/mdx-live

            - name: Run tests
              run: |
                  yarn jest
